# Generated by Django 5.2.14 on 2026-06-03 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('svg_path', models.TextField()),
                ('cx', models.FloatField()),
                ('cy', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='dashboard.district')),
            ],
            options={
                'ordering': ['district__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AreaMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('police', 'Police'), ('revenue', 'Revenue'), ('health', 'Health'), ('pds', 'PDS')], max_length=12)),
                ('primary_value', models.IntegerField()),
                ('status', models.CharField(choices=[('green', 'Normal'), ('amber', 'Watch'), ('red', 'Critical')], max_length=6)),
                ('payload', models.JSONField(default=dict)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dashboard.area')),
            ],
            options={
                'indexes': [models.Index(fields=['department', '-primary_value'], name='dashboard_a_departm_37203c_idx'), models.Index(fields=['department', 'status'], name='dashboard_a_departm_4032c3_idx')],
                'unique_together': {('area', 'department')},
            },
        ),
        migrations.CreateModel(
            name='DistrictMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('police', 'Police'), ('revenue', 'Revenue'), ('health', 'Health'), ('pds', 'PDS')], max_length=12)),
                ('primary_value', models.IntegerField()),
                ('status', models.CharField(choices=[('green', 'Normal'), ('amber', 'Watch'), ('red', 'Critical')], max_length=6)),
                ('payload', models.JSONField(default=dict)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dashboard.district')),
            ],
            options={
                'indexes': [models.Index(fields=['department', '-primary_value'], name='dashboard_d_departm_3eb866_idx'), models.Index(fields=['department', 'status'], name='dashboard_d_departm_e9c9c4_idx')],
                'unique_together': {('district', 'department')},
            },
        ),
        migrations.CreateModel(
            name='MetricPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('police', 'Police'), ('revenue', 'Revenue'), ('health', 'Health'), ('pds', 'PDS')], max_length=12)),
                ('day', models.IntegerField()),
                ('value', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='dashboard.district')),
            ],
            options={
                'ordering': ['district__name', 'department', 'day'],
                'unique_together': {('district', 'department', 'day')},
            },
        ),
    ]
