# Generated by Django 5.2.14 on 2026-06-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areametric',
            name='department',
            field=models.CharField(choices=[('police', 'Police'), ('health', 'Health'), ('pds', 'PDS')], max_length=12),
        ),
        migrations.AlterField(
            model_name='districtmetric',
            name='department',
            field=models.CharField(choices=[('police', 'Police'), ('health', 'Health'), ('pds', 'PDS')], max_length=12),
        ),
        migrations.AlterField(
            model_name='metricpoint',
            name='department',
            field=models.CharField(choices=[('police', 'Police'), ('health', 'Health'), ('pds', 'PDS')], max_length=12),
        ),
    ]
