# Generated by Django 5.2.14 on 2026-06-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_areametric_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('police', 'Police'), ('health', 'Health'), ('pds', 'PDS')], max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(unique=True)),
                ('layer', models.CharField(choices=[('source', 'Source'), ('ingestion', 'Ingestion'), ('kpi', 'KPI')], max_length=12)),
                ('description', models.CharField(max_length=220)),
                ('status', models.CharField(choices=[('live', 'Live'), ('delayed', 'Delayed'), ('offline', 'Offline')], max_length=8)),
                ('records_today', models.IntegerField()),
                ('last_sync_seconds', models.IntegerField()),
                ('latency_ms', models.IntegerField()),
                ('sort_order', models.IntegerField()),
                ('icon', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ['department', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['department', 'layer', 'sort_order'], name='dashboard_d_departm_be1cd7_idx'), models.Index(fields=['department', 'status'], name='dashboard_d_departm_7db36d_idx')],
            },
        ),
    ]
